# Generated by Django 4.0.2 on 2022-03-09 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialtutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=256)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=2056)),
                ('location', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('middle', 'middle'), ('pop-up', 'pop-up'), ('sidebar', 'sidebar')], max_length=30)),
                ('published', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('display', models.CharField(blank=True, default='', max_length=256)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=2056)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('stripe_url', models.CharField(max_length=256)),
                ('featured_image', models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('featured_video', models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('price', models.FloatField(default='0.0')),
                ('saleprice', models.FloatField(default='0.0')),
                ('onsale', models.BooleanField(default=False)),
                ('rating', models.FloatField(default='0.0')),
                ('sales', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, default='')),
                ('keys', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='socialtutorial.productkey')),
                ('tags', models.ManyToManyField(related_name='products', to='socialtutorial.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('video', models.CharField(blank=True, default='', max_length=1024)),
                ('slug', models.CharField(max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('meta_author', models.CharField(blank=True, default='Joseph Hansen', max_length=50)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('meta_url', models.CharField(blank=True, default='', max_length=64)),
                ('meta_site', models.CharField(default='Blendernomy', max_length=64)),
                ('meta_image', models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/')),
                ('meta_image_alt', models.CharField(blank=True, default='', max_length=300)),
                ('meta_twitter', models.CharField(blank=True, default='@j_claytonhansen', max_length=50)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cta', to='socialtutorial.cta')),
                ('tags', models.ManyToManyField(related_name='articles', to='socialtutorial.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
