# Generated by Django 4.0.2 on 2022-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtutorial', '0008_article_featured_on_home_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_image',
            field=models.FileField(blank=True, default='', upload_to='media/uploads/%Y/%m/%d/'),
        ),
    ]
