# Generated by Django 4.0.2 on 2022-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtutorial', '0009_alter_article_meta_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='SheepFrames',
            new_name='SheepFrame',
        ),
    ]
