# Generated by Django 4.0.2 on 2022-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtutorial', '0011_supertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supertags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='socialtutorial.SuperTag'),
        ),
    ]
