# Generated by Django 4.0.2 on 2022-03-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialtutorial', '0002_banner_cta_productkey_tag_digitalproduct_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproduct',
            name='keys',
        ),
    ]
