# Generated by Django 4.0.2 on 2022-03-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtutorial', '0005_productkey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
